trigger:
- main

variables:
  TEST1: 'idetozyml'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: FileTransform@2
  displayName: 'Replace tokens'
  inputs:
    jsonTargetFiles: '**/tests.json'

- script: |
    npm install -g @angular/cli
    npm install
    npm run test
  displayName: 'npm install and test'

- task: PublishTestResults@2
  displayName: 'Publish Angular test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS*.xml'