trigger:
- main

variables:
  TEST1: '100'
  TEST1: '50'
  TEST1: '50'
  TEST1: '50'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: replacetokens@5
  inputs:
    targetFiles: '**/environment.ts'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true


- script: |
    npm install -g @angular/cli
    npm install
    npm run test
  displayName: 'npm install and test'

- task: PublishTestResults@2
  displayName: 'Publish Angular test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS*.xml'
